version: 0.0.{build}
before_build:
- cmd: >-
    nuget restore .\src\NContract.sln
nuget:  
  disable_publish_on_pr: true
build_script:  
    - ps: .\build.ps1
test: off
deploy:
  provider: NuGet
  server:                  # remove to push to NuG
    api_key:   
        secure: 2T4gTxXWE0LX2ogqrxte/aufaaluoOVKmuuzRiIeBfQoXSu6Q0gi+S6GVvPGskFm
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
