version: 0.0.{build}
before_build:
- cmd: >-
    nuget restore .\src\NContract.sln
build:
-  cmd: >-
    nuget pack -Version %APPVEYOR_BUILD_VERSION%.
test: off
deploy:
    provider: NuGet
    api_key:    
        secure: qa3c76wngnspqk6w0hsofy21
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/



