version: 0.0.{build}
before_build:
- cmd: >-
    nuget restore .\src\NContract\packages.config -SolutionDirectory .\src\NContract.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test: off
deploy:
    provider: NuGet
    api_key:    qa3c76wngnspqk6w0hsofy21
    secure: m49OJ7+Jdt9an3jPcTukHA==
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/



