dotnet build ".\src\Examples\WebApi\WebApi.csproj"
dotnet build ".\src\Examples\WebApi.ContractTests\WebApi.ContractTests.csproj"
dotnet build ".\src\NContract.Nunit\NContract.Nunit.csproj"
dotnet build ".\src\NContract\NContract.csproj"
nuget pack ".\src\NContract\NContract.csproj.nuspec"